//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VersionDistribueeHotel.ServiceGestionDonnee {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceGestionDonneeSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceGestionDonnee : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAgencesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHotelOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChambresDisponibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback sauvegarderReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceGestionDonnee() {
            this.Url = global::VersionDistribueeHotel.Properties.Settings.Default.VersionDistribueeHotel_ServiceGestionDonnee_WebServiceGestionDonnee;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAgencesCompletedEventHandler getAgencesCompleted;
        
        /// <remarks/>
        public event getHotelCompletedEventHandler getHotelCompleted;
        
        /// <remarks/>
        public event getChambresDisponibleCompletedEventHandler getChambresDisponibleCompleted;
        
        /// <remarks/>
        public event sauvegarderReservationCompletedEventHandler sauvegarderReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAgences", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Agence[] getAgences() {
            object[] results = this.Invoke("getAgences", new object[0]);
            return ((Agence[])(results[0]));
        }
        
        /// <remarks/>
        public void getAgencesAsync() {
            this.getAgencesAsync(null);
        }
        
        /// <remarks/>
        public void getAgencesAsync(object userState) {
            if ((this.getAgencesOperationCompleted == null)) {
                this.getAgencesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAgencesOperationCompleted);
            }
            this.InvokeAsync("getAgences", new object[0], this.getAgencesOperationCompleted, userState);
        }
        
        private void OngetAgencesOperationCompleted(object arg) {
            if ((this.getAgencesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAgencesCompleted(this, new getAgencesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHotel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel getHotel() {
            object[] results = this.Invoke("getHotel", new object[0]);
            return ((Hotel)(results[0]));
        }
        
        /// <remarks/>
        public void getHotelAsync() {
            this.getHotelAsync(null);
        }
        
        /// <remarks/>
        public void getHotelAsync(object userState) {
            if ((this.getHotelOperationCompleted == null)) {
                this.getHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotelOperationCompleted);
            }
            this.InvokeAsync("getHotel", new object[0], this.getHotelOperationCompleted, userState);
        }
        
        private void OngetHotelOperationCompleted(object arg) {
            if ((this.getHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotelCompleted(this, new getHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getChambresDisponible", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Chambre[] getChambresDisponible(string dateDebut, int nbPersonne) {
            object[] results = this.Invoke("getChambresDisponible", new object[] {
                        dateDebut,
                        nbPersonne});
            return ((Chambre[])(results[0]));
        }
        
        /// <remarks/>
        public void getChambresDisponibleAsync(string dateDebut, int nbPersonne) {
            this.getChambresDisponibleAsync(dateDebut, nbPersonne, null);
        }
        
        /// <remarks/>
        public void getChambresDisponibleAsync(string dateDebut, int nbPersonne, object userState) {
            if ((this.getChambresDisponibleOperationCompleted == null)) {
                this.getChambresDisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChambresDisponibleOperationCompleted);
            }
            this.InvokeAsync("getChambresDisponible", new object[] {
                        dateDebut,
                        nbPersonne}, this.getChambresDisponibleOperationCompleted, userState);
        }
        
        private void OngetChambresDisponibleOperationCompleted(object arg) {
            if ((this.getChambresDisponibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChambresDisponibleCompleted(this, new getChambresDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sauvegarderReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sauvegarderReservation(Agence agence, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient) {
            object[] results = this.Invoke("sauvegarderReservation", new object[] {
                        agence,
                        identifiantOffre,
                        dateDebut,
                        dateFin,
                        nombrePersonnes,
                        nomClient,
                        prenomClient,
                        infoCarteCreditClient});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sauvegarderReservationAsync(Agence agence, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient) {
            this.sauvegarderReservationAsync(agence, identifiantOffre, dateDebut, dateFin, nombrePersonnes, nomClient, prenomClient, infoCarteCreditClient, null);
        }
        
        /// <remarks/>
        public void sauvegarderReservationAsync(Agence agence, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient, object userState) {
            if ((this.sauvegarderReservationOperationCompleted == null)) {
                this.sauvegarderReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsauvegarderReservationOperationCompleted);
            }
            this.InvokeAsync("sauvegarderReservation", new object[] {
                        agence,
                        identifiantOffre,
                        dateDebut,
                        dateFin,
                        nombrePersonnes,
                        nomClient,
                        prenomClient,
                        infoCarteCreditClient}, this.sauvegarderReservationOperationCompleted, userState);
        }
        
        private void OnsauvegarderReservationOperationCompleted(object arg) {
            if ((this.sauvegarderReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sauvegarderReservationCompleted(this, new sauvegarderReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Agence {
        
        private int identifiantField;
        
        private string nomField;
        
        private string loginField;
        
        private string motDePAsseField;
        
        private double pourcentageReductionField;
        
        private Adresse adresseField;
        
        private Reservation[] historiqueReservationsField;
        
        private Client[] clientsField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public string Nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string MotDePAsse {
            get {
                return this.motDePAsseField;
            }
            set {
                this.motDePAsseField = value;
            }
        }
        
        /// <remarks/>
        public double PourcentageReduction {
            get {
                return this.pourcentageReductionField;
            }
            set {
                this.pourcentageReductionField = value;
            }
        }
        
        /// <remarks/>
        public Adresse Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        public Reservation[] HistoriqueReservations {
            get {
                return this.historiqueReservationsField;
            }
            set {
                this.historiqueReservationsField = value;
            }
        }
        
        /// <remarks/>
        public Client[] Clients {
            get {
                return this.clientsField;
            }
            set {
                this.clientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Adresse {
        
        private int identifiantField;
        
        private int numeroField;
        
        private string rueField;
        
        private string paysField;
        
        private string positionGPSField;
        
        private string lieuDitField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Rue {
            get {
                return this.rueField;
            }
            set {
                this.rueField = value;
            }
        }
        
        /// <remarks/>
        public string Pays {
            get {
                return this.paysField;
            }
            set {
                this.paysField = value;
            }
        }
        
        /// <remarks/>
        public string PositionGPS {
            get {
                return this.positionGPSField;
            }
            set {
                this.positionGPSField = value;
            }
        }
        
        /// <remarks/>
        public string LieuDit {
            get {
                return this.lieuDitField;
            }
            set {
                this.lieuDitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private int identifiantField;
        
        private Adresse adresseField;
        
        private Chambre[] chambresField;
        
        private Agence[] agencesField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public Adresse Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        public Chambre[] Chambres {
            get {
                return this.chambresField;
            }
            set {
                this.chambresField = value;
            }
        }
        
        /// <remarks/>
        public Agence[] Agences {
            get {
                return this.agencesField;
            }
            set {
                this.agencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Chambre {
        
        private int identifiantField;
        
        private int numeroField;
        
        private bool estLibreField;
        
        private string dateDisponibiliteField;
        
        private float prixDeBaseField;
        
        private TypeChambre typeChambreField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public bool EstLibre {
            get {
                return this.estLibreField;
            }
            set {
                this.estLibreField = value;
            }
        }
        
        /// <remarks/>
        public string DateDisponibilite {
            get {
                return this.dateDisponibiliteField;
            }
            set {
                this.dateDisponibiliteField = value;
            }
        }
        
        /// <remarks/>
        public float PrixDeBase {
            get {
                return this.prixDeBaseField;
            }
            set {
                this.prixDeBaseField = value;
            }
        }
        
        /// <remarks/>
        public TypeChambre TypeChambre {
            get {
                return this.typeChambreField;
            }
            set {
                this.typeChambreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TypeChambre {
        
        private int nbLitsField;
        
        /// <remarks/>
        public int NbLits {
            get {
                return this.nbLitsField;
            }
            set {
                this.nbLitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Client {
        
        private int identifiantField;
        
        private string nomField;
        
        private string prenomField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public string Nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string Prenom {
            get {
                return this.prenomField;
            }
            set {
                this.prenomField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservation {
        
        private int identifiantField;
        
        private string referenceField;
        
        private string dateDebutField;
        
        private string dateFinField;
        
        private int nbPersonneField;
        
        private string informationCarteCreditField;
        
        private Client clientField;
        
        private Agence agenceField;
        
        private Chambre chambreField;
        
        /// <remarks/>
        public int Identifiant {
            get {
                return this.identifiantField;
            }
            set {
                this.identifiantField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string DateDebut {
            get {
                return this.dateDebutField;
            }
            set {
                this.dateDebutField = value;
            }
        }
        
        /// <remarks/>
        public string DateFin {
            get {
                return this.dateFinField;
            }
            set {
                this.dateFinField = value;
            }
        }
        
        /// <remarks/>
        public int NbPersonne {
            get {
                return this.nbPersonneField;
            }
            set {
                this.nbPersonneField = value;
            }
        }
        
        /// <remarks/>
        public string InformationCarteCredit {
            get {
                return this.informationCarteCreditField;
            }
            set {
                this.informationCarteCreditField = value;
            }
        }
        
        /// <remarks/>
        public Client Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        public Agence Agence {
            get {
                return this.agenceField;
            }
            set {
                this.agenceField = value;
            }
        }
        
        /// <remarks/>
        public Chambre Chambre {
            get {
                return this.chambreField;
            }
            set {
                this.chambreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getAgencesCompletedEventHandler(object sender, getAgencesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAgencesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAgencesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Agence[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Agence[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getHotelCompletedEventHandler(object sender, getHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getChambresDisponibleCompletedEventHandler(object sender, getChambresDisponibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChambresDisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChambresDisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Chambre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Chambre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sauvegarderReservationCompletedEventHandler(object sender, sauvegarderReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sauvegarderReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sauvegarderReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591