//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Agence1.ReferenceServiceReservation {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceReservationSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceReservation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback creerReservationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceReservation() {
            this.Url = global::Agence1.Properties.Settings.Default.Agence1_ReferenceServiceReservation_WebServiceReservation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event creerReservationCompletedEventHandler creerReservationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creerReservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string creerReservation(string LoginAgence, string mdp, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient) {
            object[] results = this.Invoke("creerReservation", new object[] {
                        LoginAgence,
                        mdp,
                        identifiantOffre,
                        dateDebut,
                        dateFin,
                        nombrePersonnes,
                        nomClient,
                        prenomClient,
                        infoCarteCreditClient});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void creerReservationAsync(string LoginAgence, string mdp, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient) {
            this.creerReservationAsync(LoginAgence, mdp, identifiantOffre, dateDebut, dateFin, nombrePersonnes, nomClient, prenomClient, infoCarteCreditClient, null);
        }
        
        /// <remarks/>
        public void creerReservationAsync(string LoginAgence, string mdp, string identifiantOffre, string dateDebut, string dateFin, int nombrePersonnes, string nomClient, string prenomClient, string infoCarteCreditClient, object userState) {
            if ((this.creerReservationOperationCompleted == null)) {
                this.creerReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreerReservationOperationCompleted);
            }
            this.InvokeAsync("creerReservation", new object[] {
                        LoginAgence,
                        mdp,
                        identifiantOffre,
                        dateDebut,
                        dateFin,
                        nombrePersonnes,
                        nomClient,
                        prenomClient,
                        infoCarteCreditClient}, this.creerReservationOperationCompleted, userState);
        }
        
        private void OncreerReservationOperationCompleted(object arg) {
            if ((this.creerReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.creerReservationCompleted(this, new creerReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void creerReservationCompletedEventHandler(object sender, creerReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class creerReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal creerReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591